config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :registration_steps
    resources :types
    resources :titles
    resources :users, path: 'u'
    root 'pages#root'
    get '/home', to: 'pages#home'

    resources :people do
      resources :comments, only: [:index, :new, :create ], module: :people  do
        member do
          put "like", to: "comments#upvote"
        end
      end
      get '/films', to: "people#film"
    end

    resources :movies
    resources :series
    resources :settings

    get '/catalogo', to: 'catalogue#index'
    get '/dashboard', to: 'dashboard#index'

    namespace :dashboard do
      resources :titles
      resources :people
      get '/actions', to: 'actions#index'
      post '/actions/tmbd_discover', to: 'actions#tmdb_discover'
    end
  end
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations"}
  get '', to: redirect("/#{I18n.locale}")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: :true
  belongs_to :user
  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvote]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @comment.liked_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit( :content)
    end
end

app/controllers/people/comments_controller.rb
class People::CommentsController < CommentsController
  before_action :set_commentable

  private 
  def set_commentable
    @commentable = Person.friendly.find(params[:person_id])
  end
end

app/views/comments/_comments.html.erb
<% commentable.comments.each do  |comment| %>
  <section class="Comment">
      <div class="Comment-top">
           <%= image_tag comment.user.avatar.url,  class: "Comment-userImg" %>
          <div class="Comment-cMiddle"> 
              <h4 class="Comment-nameUser"><%= comment.user.nickname %></h4>
              <p class="Comment-date"> <%= distance_of_time_in_words_to_now(comment.created_at) %> </p>
          </div>
          <div class="Comment-actions">
              <%= link_to like_person_comment_path(commentable, comment), method: :put, class: "Comment-aText" do %>
                 <i class="fa fa-thumbs-o-up"></i>
                 <%= comment.votes_for.size %> Me gusta
              <% end %>
              <a href="#" class="Comment-aText"> 
                 <i class="fa fa-comment-o"></i>
                 0 Respuestas
              </a>
              <a href="#" class="Comment-aText text-red"> 
                 <i class="fa fa-long-arrow-right"></i>
                 Responder
              </a>      
          </div>              
      </div>
      <div class="Comment-bottom">
          <p class="Comment-commentText">
              <%= comment.content %>
          </p>
      </div>
  </section>
<% end %>

app/views/comments/_form.html.erb
<h4 class="Critics-title">
    Comentarios
</h4>
<div class="FormComment">
    <%= image_tag current_user.avatar.url,  class: "FormComment-user" %>
    <div class="FormComment-formC">
        <%= form_for [commentable, Comment.new], html: {class: "FormComment-form"} do |f| %>
          <%= f.text_area :content, class: "FormComment-textArea" %>
          <%= f.submit "Crear Comentarios", class: "FormComment-formSend" %>
        <% end %>
    </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commentable</th>
      <th>Commentable type</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commentable_id %></td>
        <td><%= comment.commentable_type %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commentable:</strong>
  <%= @comment.commentable_id %>
</p>

<p>
  <strong>Commentable type:</strong>
  <%= @comment.commentable_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>