config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :registration_steps
    resources :types
    resources :titles
    resources :users, path: 'u'
    root 'pages#root'
    get '/home', to: 'pages#home'

    resources :people do
      resources :comments, only: [:index, :new, :create ], module: :people  do
        member do
          put "like", to: "comments#upvote"
        end
      end
      get '/films', to: "people#film"
    end

    resources :movies
    resources :series
    resources :settings

    get '/catalogo', to: 'catalogue#index'
    get '/dashboard', to: 'dashboard#index'

    namespace :dashboard do
      resources :titles
      resources :people
      get '/actions', to: 'actions#index'
      post '/actions/tmbd_discover', to: 'actions#tmdb_discover'
    end
  end
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations"}
  get '', to: redirect("/#{I18n.locale}")
end

app/models/person.rb
class Person < ActiveRecord::Base
  translates :biography
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :comments, as: :commentable

  has_many :crews
  has_many :titles, through: :crews
  
  has_many :casts
  has_many :titles, through: :casts
  validates :tmdb_id, uniqueness: true
  private
  def self.find_or_create_person(object, language)
    person = Person.where(tmdb_id: object.tmdb_id).first
    unless person
      I18n.locale = language
      person = Person.create(
        name: object.name,
        biography: object.biography,
        birthday: object.birthday,
        deathday: object.deathday,
        homepage: object.homepage,
        imdb_id: object.imdb_id,
        tmdb_id: object.tmdb_id,
        image: object.image,
        place_to_birth: object.place_to_birth,
        )
    end
    return person
  end
end

app/controllers/dashboard/people_controller.rb
class Dashboard::PeopleController < ApplicationController
before_action :find_post, only: [:show, :edit, :destroy, :update]
layout 'dashboard'
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 2)
  end

  def show
    @movie = Tmdb::Discover.movie()
    raise
  end
  def other
    var = 2  
    
    while var < 4
      unless Tmdb::Movie.detail(var, language: 'es')
        @movie = Tmdb::Movie.detail(var, language: 'es')
        @cast = Tmdb::Movie.cast(var)
        @video = Tmdb::Movie.videos(var)
        @credits = Tmdb::Movie.crew(var)

        @m = Title.new
        @m.title = @movie.title
        @m.overview = @movie.overview
        @m.poster = "http://image.tmdb.org/t/p/w342/" + @movie.poster_path
        @m.tagline =  @movie.tagline
        @m.type_id = 1
        unless @video
            @m.trailer =  "http://www.youtube.com/embed/" + @video[0].key 
        end  
        

        @m.tmbd_id = @movie.id
        @m.imbd_id = @movie.imdb_id
        @m.vote_average = @movie.vote_average
        @m.release_date = @movie.release_date
        @m.background = "http://image.tmdb.org/t/p/w780/" + @movie.backdrop_path
        @m.backdrop = "http://image.tmdb.org/t/p/w780/" + @movie.backdrop_path
        @m.save
        var += 1 
      end
      
    end    
  end

  def edit 

  end

  def new 
    @person = Person.new 
  end

  def create
    @person = Person.new actor_params
    if @person.save
      redirect_to dashboard_people_path, notice: "Se creo correctamente"
    else
      render 'new', notice: "Ops, ocurrio algun error"
    end
  end

  def update
    if @person.update person_params
      redirect_to dashboard_people_path, notice: "lo logramos, se actualizo"
    else
      redirecto_to 'edit', notice: "Algo salio mal"
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private 

  def find_post
    @person = Person.friendly.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :biography, :birthday, :deathday, :homepage, :imdb_id, :tmdb_id, :image, :place_to_birth)
  end

end

app/controllers/people/comments_controller.rb
class People::CommentsController < CommentsController
  before_action :set_commentable

  private 
  def set_commentable
    @commentable = Person.friendly.find(params[:person_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_post, only: [:show, :edit, :destroy, :update]
  before_action :check_details, only: [:show]
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 12)
  end

  def show

  end
  def film
    @person = Person.friendly.find(params[:person_id])
  end
  def new 
    @person = Person.new 
  end

  def create
    @person = Person.new person_params
    if @person.save
      redirect_to people_path, notice: "Se creo correctamente"
    else
      render 'new', notice: "Ops, ocurrio algun error"
    end
  end

  def update
    if @person.update people_path
      redirect_to @person, notice: "lo logramos, se actualizo"
    else
      redirecto_to 'edit', notice: "Algo salio mal"
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private 

  def find_post
    @person = Person.friendly.find(params[:id])
  end

  def person_params
    params.require(:actor).permit(:name, :biography, :birthday, :deathday, :homepage, :imdb_id, :tmdb_id, :image, :place_to_birth)
  end
  def check_details
    if @person.imdb_id == nil
      new_person = Tmdb::Person.detail(@person.tmdb_id, language: I18n.locale.to_s)
      if new_person
        @person.biography = new_person.biography if new_person.biography 
        @person.birthday = new_person.birthday if new_person.birthday
        @person.deathday = new_person.deathday if new_person.deathday
        @person.homepage = new_person.homepage if new_person.homepage
        @person.imdb_id = new_person.imdb_id if new_person.imdb_id
        @person.place_to_birth = new_person.place_of_birth if new_person.place_of_birth
        @person.save
      end
    end
  end

end

app/views/people/_filterTabActor.html.erb
<div class="InfoActor-filter">
  <%= link_to 'Información', person_path(@person), class: "InfoActor-filterText InfoActor-fActive" %>
  <%= link_to 'Filmografía', person_films_path(@person), class: "InfoActor-filterText InfoActor-fDisable" %>
</div>

app/views/people/_form.html.erb
<%= form_for @actor, html: {class: 'form'} do |f| %>
  <% if @actor.errors.any? %>
    <h2><%= pluralize(@actor.errors.count, "Error") %></h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :biography %>
    <%= f.text_area :biography %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :deathday %>
    <%= f.text_field :deathday %>
  </div>
  <div class="field">
    <%= f.label :homepage %>
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :imdb_id %>
    <%= f.text_field :imdb_id %>
  </div>
  <div class="field">
    <%= f.label :tmdb_id %>
    <%= f.text_field :tmdb_id %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :place_to_birth %>
    <%= f.text_field :place_to_birth   %>
  </div>
  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_title.html.erb
<div class="Layout-content">  
  <div class="PageTitle">
    <div class="PageTitle-infoTop">
      <h3 class="PageTitle-title PageTitle--titleBlack">
        <%= @person.name %>
      </h3>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<div class="Layout">
    <div class="Layout-page">
        <div class="Layout-content">  
          <div class="PageTitle">
              <div class="PageTitle-infoTop">
                <h3 class="PageTitle-title PageTitle--titleBlack">
                  Editar actor
                </h3>
              </div>
          </div>
        </div>
        <div class="Layout-wrapper">
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/people/film.html.erb
<div class="Layout">
  <%= render 'title' %>
  <div class="Layout-content">
    <div class="ModuleActor">
      <div class="ModuleActor-sidebarLeft">
        <div class="ModuleActor-card">
          <div class="CardActor">
            <div class="CardActor-top" style="background: url('<%= @person.image %>') 100% 100%; background-size: cover;">
            </div>
            <div class="CardActor-bottom">
              <a href="#" class="CardActor-follow">
                <i class="fa fa-eye"></i>
                  Seguir
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="ModuleActor-mainContent">
        <div class="InfoActor">
          <%= render 'filterTabActor' %>  
          <div class="InfoActor-content">
            <div class="InfoActor-tabs">
              <div class="Tabs">
                <ul class="nav nav-pills Tabs-nav" role="tablist">
                  <li role="presentation" class="active" >
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Todo</a>
                  </li>
                  <li role="presentation" >
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Director</a>
                  </li>
                  <li role="presentation"  >
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Actor</a>
                  </li>
                  <li role="presentation" >
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Guionista</a>
                  </li>
                  <li role="presentation" >
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Productor</a>
                  </li>
                  <li role="presentation">
                    <a href="#all" aria-controls="all" role="tab" data-toggle="tab">Compositor</a>
                  </li>
                </ul>  
              </div> 
            </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/people/index.html.erb
<div class="Layout">
    <div class="Layout-page">
        <div class="Layout-content">  
          <div class="PageTitle">
              <div class="PageTitle-infoTop">
                <h3 class="PageTitle-title PageTitle--titleBlack">
                  Actores
                </h3>
              </div>
          </div>
        </div>
    <div class="Layout-wrapper">
        <div class="Layout-content">
            <div class="Layout-actors">
                <% @people.each do |person| %>
                <div class="Actor">
                    <div class="Actor-top" style="background: url('<%= person.image %>') 100% 100%; background-size: cover;">  
                    </div>
                    <div class="Actor-bot">
                        <%= link_to person.name, person_path(person), class: 'Actor-name' %>
                    </div>
                </div>
                <% end %>
            </div>
            <div class="Layout-navigation">
                <div class="Navigation">
                    <%= will_paginate @people %>
                </div>
            </div>
        </div>   
    </div> 
  </div>
</div>

app/views/people/new.html.erb
<div class="Layout">
    <div class="Layout-page">
        <div class="Layout-content">  
          <div class="PageTitle">
              <div class="PageTitle-infoTop">
                <h3 class="PageTitle-title PageTitle--titleBlack">
                  Crear actor
                </h3>
              </div>
          </div>
        </div>
        <div class="Layout-wrapper">
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/people/show.html.erb
<div class="Layout">
  <%= render 'title' %>
  <div class="Layout-content">
    <div class="ModuleActor">
      <div class="ModuleActor-sidebarLeft">
        <div class="ModuleActor-card">
          <div class="CardActor">
            <div class="CardActor-top" style="background: url('<%= @person.image %>') 100% 100%; background-size: cover;">
            </div>
            <div class="CardActor-bottom">
              <a href="#" class="CardActor-follow">
                <i class="fa fa-eye"></i>
                  Seguir
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="ModuleActor-mainContent">
        <div class="InfoActor">
                  
          <div class="InfoActor-content">
            <p class="InfoActor-dataText"> Nacido en:  <span class
            ="InfoActor-text"><%= @person.place_to_birth %> </span></p>
            <p class="InfoActor-dataText"> Nacimiento:  <span class="InfoActor-text"><%= show_age(@person.birthday) %> años </span></p>
            <% if @person.homepage != "" %>
              <p class="InfoActor-dataText"> Página oficial:  <span class="InfoActor-text"> <%= @person.homepage %> </span></p>
            <% end %>
          </div>
          <h4 class="InfoActor-titleText">
            Biografía
          </h4>
          <p class="InfoActor-biography">
           <%= @person.biography %>
          </p>
          <h4 class="InfoActor-titleText">
            Últimos trabajos
          </h4>
          <div class="InfoActor-lastWorksC">
            <% @person.casts.each do |f| %>
              <div class="CardMedia">
                <%= link_to movie_path(f.title) , class: "CardMedia-top" do %>
                  <img src="<%= f.title.poster %>" class="CardMedia-img">
                  </img>
                <% end %>
                <div class="CardMedia-bottomLarge">
                  <%= link_to movie_path(f.title) , class: "CardMedia-cTitle CardMedia--titleGrey" do %>
                    <p class="CardMedia-mainText CardMedia--titleGrey"> <%= truncate(f.title.title) %> </p>
                  <% end %>
                  <a class="CardMedia-iconEllipsis">
                    <i class="fa fa-ellipsis-v"></i>
                  </a>
                  <div class="CardMedia-hiddenData">
                    <a href="#" class="CardMedia-linkHidden"> Vista </a>
                    <a href="#" class="CardMedia-linkHidden"> Pendiente </a>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="InfoActor-comments">
              <div class="Critics">
                    <%= render partial: "comments/form", locals: {commentable: @person} %>
                <div class="Critics">
                    <div class="Critics-comments">
                        <div class="Critics-filter">
                            <a href="#" class="Critics-fText Critics--fActive"> Comentarios Populares</a>
                        </div>
                        <%= render partial: "comments/comments", locals: {commentable: @person} %>
                    </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>