config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :registration_steps
    resources :types
    resources :titles
    resources :users, path: 'u'
    root 'pages#root'
    get '/home', to: 'pages#home'

    resources :people do
      resources :comments, only: [:index, :new, :create ], module: :people  do
        member do
          put "like", to: "comments#upvote"
        end
      end
      get '/films', to: "people#film"
    end

    resources :movies
    resources :series
    resources :settings

    get '/catalogo', to: 'catalogue#index'
    get '/dashboard', to: 'dashboard#index'

    namespace :dashboard do
      resources :titles
      resources :people
      get '/actions', to: 'actions#index'
      post '/actions/tmbd_discover', to: 'actions#tmdb_discover'
    end
  end
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations"}
  get '', to: redirect("/#{I18n.locale}")
end

app/models/person.rb
class Person < ActiveRecord::Base
  translates :biography
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :comments, as: :commentable

  has_many :crews
  has_many :titles, through: :crews
  
  has_many :casts
  has_many :titles, through: :casts
  validates :tmdb_id, uniqueness: true
  private
  def self.find_or_create_person(object, language)
    person = Person.where(tmdb_id: object.tmdb_id).first
    unless person
      I18n.locale = language
      person = Person.create(
        name: object.name,
        biography: object.biography,
        birthday: object.birthday,
        deathday: object.deathday,
        homepage: object.homepage,
        imdb_id: object.imdb_id,
        tmdb_id: object.tmdb_id,
        image: object.image,
        place_to_birth: object.place_to_birth,
        )
    end
    return person
  end
end

app/controllers/dashboard/actions_controller.rb
class Dashboard::ActionsController < ApplicationController
  layout 'dashboard'
  def index
    @total_comments = Comment.count
    @total_users = User.count
    @total_titles = Title.count
    @total_people = Person.count
  end
  def tmdb_discover
    @discover = tmbdApi_params
    if @discover[:type] == "movie"
      
      how_much = @discover[:how_much].to_i
      number_repeat = (how_much/20).round
      (1..number_repeat).each do |page|
        @discover[:page] = page.to_s
        movies = Tmdb::Discover.movie(@discover)
        movies.results.each do |movie|
          new_title = Title.new
          new_title = create_object(new_title,movie) 
          new_title = Title.find_or_update_by_scrapper(new_title,new_title.tmbd_id,@discover[:language].to_sym )
        end
      end
      flash[:notice] = "Completado"
      redirect_to :back
    elsif @discover[:type] =="series"

    else
      redirect_to :back
    end

  end
  private
  def tmbdApi_params
    params.require(:scraper).permit(:sort_by, :include_adult, :type, :language, :release_from_year, :release_to_year, :how_much)
  end
  def create_object(object,result)
    #if state is update if not save
    object.title = result.title
    object.overview = result.overview
    object.tagline =  ""
    if result.poster_path == nil
      object.poster = ""
    else
      object.poster = "http://image.tmdb.org/t/p/w342/" + result.poster_path
    end
    object.type_id = 1
    if result.imdb_id == nil
      object.imbd_id = ""
    else
      object.imbd_id = result.imdb_id
    end
    object.tmbd_id = result.id
    object.vote_average = result.vote_average
    object.release_date = result.release_date
    if result.backdrop_path == nil
      object.background = ""
      object.backdrop = ""
    else
      object.background = "http://image.tmdb.org/t/p/w1280/" + result.backdrop_path 
      object.backdrop = "http://image.tmdb.org/t/p/w780/" + result.backdrop_path 
    end
    return object
  end
end

app/controllers/dashboard/people_controller.rb
class Dashboard::PeopleController < ApplicationController
before_action :find_post, only: [:show, :edit, :destroy, :update]
layout 'dashboard'
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 2)
  end

  def show
    @movie = Tmdb::Discover.movie()
    raise
  end
  def other
    var = 2  
    
    while var < 4
      unless Tmdb::Movie.detail(var, language: 'es')
        @movie = Tmdb::Movie.detail(var, language: 'es')
        @cast = Tmdb::Movie.cast(var)
        @video = Tmdb::Movie.videos(var)
        @credits = Tmdb::Movie.crew(var)

        @m = Title.new
        @m.title = @movie.title
        @m.overview = @movie.overview
        @m.poster = "http://image.tmdb.org/t/p/w342/" + @movie.poster_path
        @m.tagline =  @movie.tagline
        @m.type_id = 1
        unless @video
            @m.trailer =  "http://www.youtube.com/embed/" + @video[0].key 
        end  
        

        @m.tmbd_id = @movie.id
        @m.imbd_id = @movie.imdb_id
        @m.vote_average = @movie.vote_average
        @m.release_date = @movie.release_date
        @m.background = "http://image.tmdb.org/t/p/w780/" + @movie.backdrop_path
        @m.backdrop = "http://image.tmdb.org/t/p/w780/" + @movie.backdrop_path
        @m.save
        var += 1 
      end
      
    end    
  end

  def edit 

  end

  def new 
    @person = Person.new 
  end

  def create
    @person = Person.new actor_params
    if @person.save
      redirect_to dashboard_people_path, notice: "Se creo correctamente"
    else
      render 'new', notice: "Ops, ocurrio algun error"
    end
  end

  def update
    if @person.update person_params
      redirect_to dashboard_people_path, notice: "lo logramos, se actualizo"
    else
      redirecto_to 'edit', notice: "Algo salio mal"
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private 

  def find_post
    @person = Person.friendly.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :biography, :birthday, :deathday, :homepage, :imdb_id, :tmdb_id, :image, :place_to_birth)
  end

end

app/controllers/dashboard/settings_controller.rb
class Dashboard::SettingsController < ApplicationController
end

app/controllers/dashboard/titles_controller.rb
class Dashboard::TitlesController < ApplicationController
  layout 'dashboard'
   before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to dashboard_titles_path, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to dashboard_titles_path, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:title, :type_id, :overview, :poster, :tagline, :trailer, :imbd_id, :tmbd_id, :vote_average, :release_date, :background, :runtime, :status, :budget, :revenue, :country, :backdrop, :website)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
  end
end

app/controllers/people/comments_controller.rb
class People::CommentsController < CommentsController
  before_action :set_commentable

  private 
  def set_commentable
    @commentable = Person.friendly.find(params[:person_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_post, only: [:show, :edit, :destroy, :update]
  before_action :check_details, only: [:show]
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 12)
  end

  def show

  end
  def film
    @person = Person.friendly.find(params[:person_id])
  end
  def new 
    @person = Person.new 
  end

  def create
    @person = Person.new person_params
    if @person.save
      redirect_to people_path, notice: "Se creo correctamente"
    else
      render 'new', notice: "Ops, ocurrio algun error"
    end
  end

  def update
    if @person.update people_path
      redirect_to @person, notice: "lo logramos, se actualizo"
    else
      redirecto_to 'edit', notice: "Algo salio mal"
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

  private 

  def find_post
    @person = Person.friendly.find(params[:id])
  end

  def person_params
    params.require(:actor).permit(:name, :biography, :birthday, :deathday, :homepage, :imdb_id, :tmdb_id, :image, :place_to_birth)
  end
  def check_details
    if @person.imdb_id == nil
      new_person = Tmdb::Person.detail(@person.tmdb_id, language: I18n.locale.to_s)
      if new_person
        @person.biography = new_person.biography if new_person.biography 
        @person.birthday = new_person.birthday if new_person.birthday
        @person.deathday = new_person.deathday if new_person.deathday
        @person.homepage = new_person.homepage if new_person.homepage
        @person.imdb_id = new_person.imdb_id if new_person.imdb_id
        @person.place_to_birth = new_person.place_of_birth if new_person.place_of_birth
        @person.save
      end
    end
  end

end

app/views/dashboard/people/_form.html.erb
<%= form_for [:dashboard , @person] do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :biography %>
    <%= f.text_area :biography, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :birthday %>
    <%= f.text_field :birthday, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :deathday %>
    <%= f.text_field :deathday , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :homepage %>
    <%= f.text_field :homepage, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :imdb_id %>
    <%= f.text_field :imdb_id , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :tmdb_id %>
    <%= f.text_field :tmdb_id , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.text_field :image , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :place_to_birth %>
    <%= f.text_field :place_to_birth , class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/dashboard/people/edit.html.erb
<div id="wrapper">
  <%= render '/dashboard/partials/nav' %>
  <!--/. NAV TOP  -->
        
  <%= render '/dashboard/partials/menu' %>
    
  <div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-header">
                    Editar
                </h1>
            </div>
        </div>
        <div class="row">
          <div class="col-md-12">
             <%= render 'form' %>
          </div>  
        </div>
          <%= link_to 'Regresar', dashboard_people_path %>
    </div>
  </div>


</div> 

app/views/dashboard/people/index.html.erb
<div id="page-inner">
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">
                Titulos
            </h1>
        </div>
    </div>       
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                Películas
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <%= link_to new_dashboard_title_path, class: "btn btn-primary btn-lg" do %>
                       <i class="fa fa-plus"></i> Crear Titulo</a>
                    <% end %>
                    
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Imagen</th>
                                <th>Nombre</th>
                                <th>Biografia</th>
                                <th>Cumpleaños</th>
                                <th>Lugar de Nacimiento</th>
                                <th>Creado en</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @people.each do |person| %>
                              <tr>
                                  <td><%= image_tag person.image, class: "poster-medium" %></td>
                                  <td><%= person.name %></td>
                                  <td><%= truncate person.biography %></td>
                                  <td><%= person.birthday %> </td>
                                  <td><%= person.place_to_birth %></td>
                                  <td><%= person.created_at %></td>
                                  <td>
                                    <%= link_to edit_dashboard_person_path(person), class: "btn-primary btn" do %>
                                        <i class="fa fa-edit "></i> Editar
                                    <% end %>
                                    <%= link_to dashboard_person_path(person), method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger" do %>
                                        <i class="fa fa-pencil"></i> Borrar</button>
                                    <% end %>
                                  </td>
                              </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
          </div>
        </div>
    </div>
    <!-- /. ROW  -->
    <footer><p>All right reserved. </footer>
</div>